name: CI/CD pipeline

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: chaimagharbi/my-app

    steps:
    - name: Checkout repo
      uses: actions/Checkout@v3

    - name: Log in Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE_TAG=$IMAGE_NAME:$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t $IMAGE_TAG .

    - name: Push Docker image
      run:
        docker push $IMAGE_TAG

    - name: Update deployment image
      run: |
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_TAG|g" k8s/deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add k8s/deployment.yaml
        git commit -m "Update deployment image to $IMAGE_TAG" || echo "No changes"
        git push origin main
